### ISSUE TITLE
KeyError: 'attributes' for optuna-param-path config file

### ISSUE THREAD

**Issue by pvcastro** [himkt/allenopt#38] opened 2021-05-04 12:52 UTC
Hi there!

Great work on this plugin!

I'm running a test here, and I'm using the following optuna-param-path config file. I was just expecting to specify the pruner and sampler, without specifying actual attributes for them (leave the default). Looks like the tune command expects some attributes, is this really necessary?

Thanks!

```
{
    "pruner": {
        "type": "SuccessiveHalvingPruner"
    },
    "sampler": {
        "type": "TPESampler"
    }
}
```

```
2021-05-04 09:44:54,905 - INFO - allennlp.common.plugins - Plugin allennlp_models available
2021-05-04 09:44:54,971 - INFO - allennlp.common.plugins - Plugin allennlp_server available
2021-05-04 09:44:55,514 - INFO - allennlp.common.plugins - Plugin allennlp_optuna available
Traceback (most recent call last):
  File "/media/discoD/anaconda3/envs/allennlp/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/media/discoD/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/media/discoD/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 119, in main
    args.func(args)
  File "/media/discoD/anaconda3/envs/allennlp/lib/python3.7/site-packages/allennlp_optuna/commands/tune.py", line 66, in tune
    pruner = pruner_class(**optuna_config["pruner"]["attributes"])
KeyError: 'attributes'
```

**Comment by himkt** [comment] 2021-05-06 13:54
Hello @pvcastro! Thank you so much for trying `allennlp-optuna`.
As you pointed out, `allennlp-optuna` currently doesn't allow users to specify samplers/pruners without `attributes`.
After #40 being merged, you can use a sampler or pruner with the configuration you shared.

**Comment by himkt** [comment] 2021-05-06 15:05
#40 was merged. You can skip specifying `attributes` from the next release of allennlp-optuna.

**Comment by pvcastro** [comment] 2021-05-06 18:09
Great, thanks @himkt !
As soon as my current search finishes, I'll try this new version.

**Comment by himkt** [comment] 2021-05-09 08:12
I released allennlp-optuna v0.1.6 just now. It fixes the problem!

https://github.com/himkt/allennlp-optuna/releases/tag/v0.1.6

**Comment by pvcastro** [comment] 2021-05-12 18:52
Hi @himkt !
Sorry for taking so long, but I was waiting for my last tune to finish...it was running for some days.

I just tried running it again without specifying any parameters, and now the error is this:

```
Traceback (most recent call last):
  File "/opt/conda/envs/allennlp/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/__main__.py", line 34, in run
    main(prog="allennlp")
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 119, in main
    args.func(args)
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp_datalawyer/tune/tune_cv.py", line 158, in tune_cv
    study.optimize(objective_cv, n_trials=n_trials, timeout=timeout)
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/optuna/study.py", line 400, in optimize
    _optimize(
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/optuna/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/optuna/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/optuna/_optimize.py", line 268, in _run_trial
    raise func_err
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/optuna/_optimize.py", line 217, in _run_trial
    value_or_values = func(trial)
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp_datalawyer/tune/tune_cv.py", line 117, in _objective_cv
    train_loop = TrainModel.from_params(
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 589, in from_params
    return retyped_subclass.from_params(
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 623, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/commands/train.py", line 729, in from_partial_objects
    trainer_ = trainer.construct(
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/common/lazy.py", line 80, in construct
    return self.constructor(**contructor_kwargs)
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/common/lazy.py", line 64, in constructor_to_use
    return self._constructor.from_params(  # type: ignore[union-attr]
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 589, in from_params
    return retyped_subclass.from_params(
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 623, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/training/trainer.py", line 1068, in from_partial_objects
    callbacks_.append(callback_.construct(serialization_dir=serialization_dir))
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/common/lazy.py", line 80, in construct
    return self.constructor(**contructor_kwargs)
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/common/lazy.py", line 64, in constructor_to_use
    return self._constructor.from_params(  # type: ignore[union-attr]
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 589, in from_params
    return retyped_subclass.from_params(
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/allennlp/common/from_params.py", line 623, in from_params
    return constructor_to_call(**kwargs)  # type: ignore
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/optuna/_experimental.py", line 90, in wrapped_init
    _original_init(self, *args, **kwargs)
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/optuna/integration/allennlp.py", line 464, in __init__
    study = load_study(study_name, storage, pruner=_create_pruner())
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/optuna/integration/allennlp.py", line 95, in _create_pruner
    return pruner(**pruner_params)
  File "/opt/conda/envs/allennlp/lib/python3.8/site-packages/optuna/pruners/_successive_halving.py", line 121, in __init__
    raise ValueError(
ValueError: The value of `min_resource` is None, but must be either `min_resource` >= 1 or 'auto'
```

**Comment by himkt** [comment] 2021-05-14 13:52
Hmm, sorry for the inconvenience.
Can you share your config file you used? (optuna param file (json) and allennlp config file (jsonnet))

**Comment by himkt** [comment] 2021-05-14 13:56
@pvcastro

**Comment by pvcastro** [comment] 2021-05-14 14:32
Hi @himkt !

optuna.json was just:

```
{
    "pruner": {
        "type": "SuccessiveHalvingPruner"
    }
}
```

the callback config from jsonnet was:

```
callbacks: [
            {
                type: 'optuna_pruner'
            }
        ],
```

Do you think you need the whole config file? I'm thinking these should be enough, right?

**Comment by himkt** [comment] 2021-05-15 08:03
@pvcastro 

Thank you for sharing the configurations. I identified the cause, and I'm working on fixing it.
Can we close this issue and move to #39 for further discussion?

**Comment by pvcastro** [comment] 2021-05-15 13:33
Sure @himkt , fine by me.

**Comment by himkt** [comment] 2021-05-15 16:11
Thank you! Let me close it.

**Closed as completed by himkt** 2021-05-15 16:11 UTC
Labels: bug
